- name: jboss
  port: 8080
  targetPort: 8080
- name: ejb
  port: 4447
  targetPort: 4447
- name: http
  port: 80
  targetPort: 80
- name: https
  port: 443
  targetPort: 443
- name: metrics
  port: 9600
  targetPort: 9600