- name: ENM_JBOSS_BIND_ADDRESS
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
- name: ENM_JBOSS_JGROUPS_BIND_ADDRESS
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
- name: ENM_JBOSS_SDK_CLUSTER_ID
  value: {{ .Values.service.name }}
{{- if .Values.global.enmProperties.postgres_service }}
- name: POSTGRES_SERVICE
  value: {{ .Values.global.enmProperties.postgres_service }}
{{- end }}
