- name: UI_PRES_SERVER
  value: {{ template "eric-enm-common-helmchart-library.enmHost" . }}
- name: web_host_default
  value: {{ template "eric-enm-common-helmchart-library.enmHost" . }}
- name: TZ
  value: {{ .Values.global.timezone }}
