- name: gp
  configMap:
    name: gpaccesscontrol
- name: data
  persistentVolumeClaim:
    claimName: data
- name: smrs
  persistentVolumeClaim:
    claimName: smrs
- name: mdt
  persistentVolumeClaim:
    claimName: mdt
- name: custom
  persistentVolumeClaim:
    claimName: custom
- name: dumps
  persistentVolumeClaim:
    claimName: hcdumps
- name: batch
  persistentVolumeClaim:
    claimName: batch
- name: norollback
  persistentVolumeClaim:
    claimName: norollback
- name: configmgt
  persistentVolumeClaim:
    claimName: configmgt
- name: upgind
  persistentVolumeClaim:
    claimName: upgind
- name: pmic1
  persistentVolumeClaim:
    claimName: pm1
- name: pmic2
  persistentVolumeClaim:
    claimName: pm2
- name: pmlinks
  persistentVolumeClaim:
    claimName: pmlinks
